### PR TITLE
Grafts are in bay beeeee

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

alright quick n dirty 5am bedpost desc.
snip grown plants to get a graft
grafts carry over select traits between plants. Most plants either have their key trait, or just give repeated harvest
key feature is that they give most of their stats to the graftee, giving the highest of either:
 the parent's stats
 the grafter's stats - the graftee's stats * 2/3
so that you can't infinitely chain grafts to max out all stats, but you can still get good amounts of stats at a time per graft. effetively encourages boosting individual stats to get the graftee's stats up every generation
probably done with some shitcode because I took an 11 day break inbeween
still works, don't @ me

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
I'll fix conflicts later

**Comment by ArcaneMusic** [comment]
Alright I unfucked everything and it should ALSO be updating everything, NICE

**Comment by ArcaneMusic** [comment]
@kriskog Yeah this works now, merge at your discretion.

**Comment by kriskog** [comment]
Looks okay. For grafting I had planned being able to share some traits as you are and certain stats like endurance and yield but not necessarily potency. We may need to revisit that later, but until then this is a good framework. Depends how we do crossbreeds and splicing.

**Pull request merged**
